@startuml

abstract class Animal {
    -name: String
    -age: int
    +getName(): String
    +getAge(): int
    +makeSound(): String
}

class Dog extends Animal {
    -breed: String
    +getBreed(): String
    +makeSound(): String
}

class Cat extends Animal {
    -furColor: String
    +getFurColor(): String
    +makeSound(): String
}

@enduml
