name: Python Package

on: push

jobs:
    build:
        name: Build Package
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup
              uses: actions/setup-python@v3

            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                python -m pip install requests beautifulsoup4 selenium pytest

            - name: Run Tests
              run: |
                pytest